### ISSUE TITLE
Verifying correctness - HR / SM

### ISSUE THREAD

**Issue by VaradK62442** [sofiatolaosebikan/algmatch#10]
Follow standard structure of generate instance -> brute force all stable matchings -> check generated stable matchings are what they should be.

**Comment by BenOnTheBoard** [comment]
Update:
- SM tests work
- SM algorithms are broken
- I will include the branch for this issue
- I will push when the SM algorithms clear all tests

**Comment by BenOnTheBoard** [comment]
Update:
- very minor issue with the check_stability method which has bene easily rectified; checking alg was using the original ranking on the lists after deletion had been made
- I'm running some larger scale tests on the SM algorithm now, everything is looking good.
- I will push this section shortly
