### ISSUE TITLE
Final changes for first release

### ISSUE THREAD

**Issue by VaradK62442** [sofiatolaosebikan/algmatch#32]
Get package ready for deployment essentially.
Here is what I can think of currently:

- [x] change formatting syntax (`from algmatch.matchingAlg import MatchingAlg` -> `from algmatch import MatchingAlg`)
- [x] change `SPAInstanceGenerator` name
- [x] remove temp in readme
- [x] requirements.txt (e.g. tqdm)

**Comment by VaradK62442** [comment]
@BenOnTheBoard lmk if you can think of any other final touches

**Comment by BenOnTheBoard** [comment]
I have time later tonight so I'll close up the example notebook issue.

**Comment by VaradK62442** [comment]
oh i can look at that now if you want
was just about to start on it

**Comment by BenOnTheBoard** [comment]
Declaring this done barring minor changes we may make tomorrow.
