### ISSUE TITLE
Perspective of Returned Stable Matchings

### ISSUE THREAD

**Issue by BenOnTheBoard** [sofiatolaosebikan/algmatch#6]
Currently:
- the resulting matching for SM is a dictionary with the men as keys
- the resulting matching for HR is a dictionary with the residents as keys
- the resulting matching for SPA is a dictionary with the students as keys

Proposal:
Either: Allow the user to specify which side of the matching should be used as the key.
Or: Include both perspectives together in the stable_matching dictionary.

Rationale for creating this issue:
I noticed this issue while check the results of the hospital-oriented HR algorithm against an existing example. The correct answer was given with the hospitals as the keys and sets of residents as values. Checking that each hospital had the correct set of residents was more effort since, in our current code, residents are being used as keys.
This is relevant in the HR and SPA cases, because it is often simpler and more efficient to use set operations, and because it is neater to show the matching in this way.
I made this an issue in order to get your feedback on which of the above options you think is preferable.

**Comment by VaradK62442** [comment]
yea this is a good point, of the two options, including both perspectives seems better to me. we'd be doing the same work for either one regardless, just have to see which is more usable. with user being given both options they don't then need to re-run the algorithm to see the other one

**Comment by BenOnTheBoard** [comment]
The operator ':=' causes strange outputs.
Separating out the statement into two lines fixes this issue.
Python version: 3.12.3

**Comment by BenOnTheBoard** [comment]
Expected output:
{'man_sided': {'m1': 'w2', 'm2': 'w4', 'm3': 'w1', 'm4': 'w3'}, 'woman_sided': {'w1': 'm3', 'w2': 'm1', 'w3': 'm4', 'w4': 'm2'}}

Actual ouput:
{'man_sided': {'m1': True, 'm2': True, 'm3': True, 'm4': True}, 'woman_sided': {'w1': '', 'w2': '', 'w3': '', 'w4': '', True: 'm4'}}
