### ISSUE TITLE
File format checks

### ISSUE THREAD

**Issue by VaradK62442** [sofiatolaosebikan/algmatch#9]
Files provided are not checked against the format they should be and so the error thrown isn't useful.

**Comment by VaradK62442** [comment]
Dictionaries aren't checked either

**Comment by BenOnTheBoard** [comment]
Note:
The pass that handles the setup of rankings will now be handled by the relevant PreferenceInstance class for the problem.
Each class has a single responsibility now:
- FileReader -> read preference lists from file
- DictionaryReader -> read preference lists from dictionary
- smPreferenceInstance -> pre-process instances for algorithms (inc. removing unacceptable pairs and setting up the ranking dictionaries)
